OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Models/Movies/DeleteMovieViewModel.cs
using System;

namespace OnLineVideotech.Web.Areas.Admin.Models.Movies
{
    public class DeleteMovieViewModel
    {
        public Guid Id { get; set; }

        public string MovieName { get; set; }
    }
}

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Controllers/MovieManagementController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnLineVideotech.Data.Models;
using OnLineVideotech.Services.Admin.Interfaces;
using OnLineVideotech.Services.Admin.ServiceModels;
using OnLineVideotech.Web.Areas.Admin.Models;
using OnLineVideotech.Web.Areas.Admin.Models.Movies;
using OnLineVideotech.Web.Infrastructure.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnLineVideotech.Web.Areas.Admin.Controllers
{
    public class MovieManagementController : BaseAdminController
    {
        private readonly IMovieManagementService moviesService;
        private readonly UserManager<User> userManager;
        private readonly IRoleService roleService;
        private readonly IGenreService genreService;

        public MovieManagementController(
            IMovieManagementService moviesService,
            UserManager<User> userManager,
            IRoleService roleService,
            IGenreService genreService)
        {
            this.moviesService = moviesService;
            this.userManager = userManager;
            this.roleService = roleService;
            this.genreService = genreService;
        }

        public async Task<IActionResult> CreateMovie()
        {
            IEnumerable<Role> roles = await roleService.GetAllRoles();
            IEnumerable<GenreServiceModel> genres = await genreService.GetAllGenres();

            MovieAdminViewModel model = new MovieAdminViewModel();
            model.Prices = new List<PriceServiceModel>();
            model.Genres = new List<GenreServiceModel>();

            foreach (Role role in roles)
            {
                PriceServiceModel priceModel = new PriceServiceModel();
                priceModel.RoleId = role.Id;
                priceModel.Role = role;
                model.Prices.Add(priceModel);
            }

            foreach (GenreServiceModel genre in genres)
            {
                GenreServiceModel genreModel = new GenreServiceModel();
                genreModel.Name = genre.Name;
                genreModel.Id = genre.Id;
                model.Genres.Add(genreModel);
            }

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateMovie(MovieAdminViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.moviesService.Create(
                model.Name,
                model.Year,
                model.Rating,
                model.VideoPath,
                model.PosterPath,
                model.TrailerPath,
                model.Summary,
                model.Prices,
                model.Genres);

            TempData.AddSuccessMessage($"Movie '{model.Name}' successfully created");

            return RedirectToAction(nameof(CreateMovie));
        }

        public async Task<IActionResult> EditMovie(Guid id)
        {
            MovieAdminServiceModel movie = await this.moviesService.FindMovie(id);
            MovieAdminViewModel model = new MovieAdminViewModel
            {
                Id = movie.Id,
                Name = movie.Name,
                Year = movie.Year,
                Rating = movie.Rating,
                VideoPath = movie.VideoPath,
                PosterPath = movie.PosterPath,
                TrailerPath = movie.TrailerPath,
                Summary = movie.Summary,
                Prices = movie.Prices,
                Genres = movie.Genres
            };

            return this.View(model);
        }

        [HttpPost]
        public IActionResult EditMovie(MovieAdminViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            this.moviesService.EditMovie(
                model.Id,
                model.Name,
                model.Year,
                model.Rating,
                model.VideoPathEdit,
                model.PosterPath,
                model.TrailerPath,
                model.Summary,
                model.Prices,
                model.Genres);

            TempData.AddSuccessMessage($"Movie '{model.Name}' successfully edited !");

            return RedirectToAction(nameof(EditMovie));
        }

        public async Task<IActionResult> DeleteMovie(Guid id)
        {
            MovieAdminServiceModel movie = await this.moviesService.FindMovie(id);
            DeleteMovieViewModel movieModel = new DeleteMovieViewModel();

            movieModel.MovieName = movie.Name;
            movieModel.Id = movie.Id;

            return View(movieModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMovie(DeleteMovieViewModel model)
        {
            if (!ModelState.IsValid)
            {
                //var errors = ModelState.Select(x => x.Value.Errors)
                //           .Where(y => y.Count > 0)
                //           .ToList();

                return View(model);
            }

            await this.moviesService.DeleteMovie(model.Id);

            TempData.AddSuccessMessage($"Movie '{model.MovieName}' successfully deleted !");

            return RedirectToAction("Index", "Movie");
        }
    }
}

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Views/MovieManagement/Add.cshtml
@model AddMovieViewModel;

@{
    ViewData["Title"] = "Add Movie";
}

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <h4>Create a new movie</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Movie name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year"></label>
                <input asp-for="Year" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoPath">Movie file</label>
                <input asp-for="VideoPath" type="file" class="form-control" />
                <span asp-validation-for="VideoPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PosterPath">Poster</label>
                <input asp-for="PosterPath" type="url" class="form-control" />
                <span asp-validation-for="PosterPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrailerPath">Trailer</label>
                <input asp-for="TrailerPath" type="url" class="form-control" />
                <span asp-validation-for="TrailerPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summary">Summary</label>
                <textarea asp-for="Summary" rows="5" class="form-control"></textarea>
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Add Movie</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Views/MovieManagement/AddGenreToMovie.cshtml
@model MovieAdminViewModel;

<h4><b>Step 2:</b> Movie genres</h4>
@for (int i = 0; i < Model.Genres.Count; i++)
{
    <div class="form-check form-check-inline">
        <input asp-for="@Model.Genres[i].IsSelected" class="form-check-input" type="checkbox">
        <label class="form-check-label">@Model.Genres[i].Name</label>
        <input type="hidden" asp-for="@Model.Genres[i].Id" value="@Model.Genres[i].Id" class="form-control" />       
    </div>
}

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Views/MovieManagement/AddMovieDescription.cshtml
@model MovieAdminViewModel;

@{
    ViewData["Title"] = "Add movie description";
}

<h4><b>Step 1:</b> Movie information</h4>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Name"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Year"></label>
    <input asp-for="Year" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control" />
    <span asp-validation-for="Year" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Rating"></label>
    <input asp-for="Rating" class="form-control" />
    <span asp-validation-for="Rating" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="VideoPath"></label>

    @if (Model.VideoPath != null)
    {
        <br />
        <label>@Model.VideoPath - Change video path:</label>
        <input asp-for="VideoPathEdit" type="file" class="form-control" />
        <span asp-validation-for="VideoPathEdit" class="text-danger"></span>
        <input type="hidden" asp-for="@Model.VideoPath" value="@Model.VideoPath" class="form-control" />
    }
    else
    {
        <input asp-for="VideoPath" type="file" class="form-control" />
        <span asp-validation-for="VideoPath" class="text-danger"></span>
        <input type="hidden" asp-for="@Model.VideoPath" value="@Model.VideoPath" class="form-control" />
    }

</div>
<div class="form-group">
    <label asp-for="PosterPath"></label>
    <input asp-for="PosterPath" type="url" class="form-control" />
    <span asp-validation-for="PosterPath" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="TrailerPath"></label>
    <input asp-for="TrailerPath" type="url" class="form-control" />
    <span asp-validation-for="TrailerPath" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Summary"></label>
    <textarea asp-for="Summary" rows="10" class="form-control"></textarea>
    <span asp-validation-for="Summary" class="text-danger"></span>
</div>

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Views/MovieManagement/AddMoviePrice.cshtml
@model MovieAdminViewModel;

<hr />
<h4><b>Step 3:</b> Movie price for different types of user</h4>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                Role
            </th>
            <th>
                Price
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Prices.Count; i++)
        {
            <tr>
                <th>
                    @Model.Prices[i].Role.Name
                </th>
                <th>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <input type="hidden" name="RoleId" value="@Model.Prices[i].Role.Id" />
                                <input asp-for="@Model.Prices[i].Price" class="form-control" />
                                <span asp-validation-for="@Model.Prices[i].Price" class="text-danger"></span>

                                <input type="hidden" asp-for="@Model.Prices[i].Id" value="@Model.Prices[i].Id" class="form-control" />
                                <input type="hidden" asp-for="@Model.Prices[i].RoleId" value="@Model.Prices[i].RoleId" class="form-control" />
                                <input type="hidden" asp-for="@Model.Prices[i].Role.Name" value="@Model.Prices[i].Role.Name" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <b>BGN</b>
                        </div>
                    </div>
                </th>
            </tr>
        }
    </tbody>
</table>

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Views/MovieManagement/CreateMovie.cshtml
@model MovieAdminViewModel;

@{
    ViewData["Title"] = "Create movie";
}

<form asp-controller="MovieManagement" asp-action="AddMovie" method="post">
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <h3>Add a new movie</h3>
            <br />
            @await Html.PartialAsync("AddMovieDescription", Model)
            @await Html.PartialAsync("AddGenreToMovie", Model)
            @await Html.PartialAsync("AddMoviePrice", Model)

            <button class="btn btn-info btn-lg btn-block">Create movie</button>
        </div>
        <div class="col-md-1">
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Views/MovieManagement/DeleteMovie.cshtml
@model DeleteMovieViewModel;

@{
    ViewData["Title"] = "Delete movie";
}

<h4>Are you sure you want to delete movie "@Model.MovieName" ?</h4>
<hr />

<form asp-controller="MovieManagement" asp-action="DeleteMovie" method="post">
    <input type="hidden" asp-for="@Model.MovieName" value="@Model.MovieName" class="form-control" />
    <input type="hidden" asp-for="@Model.Id" value="@Model.Id" class="form-control" />
    <span asp-validation-for="MovieName"></span>
    <div>
        <input class="btn btn-sm btn-danger" type="submit" value="Yes, delete !" />
    </div>
</form>

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Views/MovieManagement/EditMovie.cshtml
@model MovieAdminViewModel;

@{
    ViewData["Title"] = "Edit movie";
}

@{
    ViewData["Title"] = "Create movie";
}

<form asp-controller="MovieManagement" asp-action="EditMovie" method="post">
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <h3>Edit Movie</h3>
            <br />
            @await Html.PartialAsync("AddMovieDescription", Model)
            @await Html.PartialAsync("AddGenreToMovie", Model)
            @await Html.PartialAsync("AddMoviePrice", Model)

            <button class="btn btn-info btn-lg btn-block">Save</button>
        </div>
        <div class="col-md-1">
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}