OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using OnLineVideotech.Services.Admin.Interfaces;
using OnLineVideotech.Services.Admin.ServiceModels;
using OnLineVideotech.Web.Areas.Admin.Models.Genres;
using OnLineVideotech.Web.Infrastructure.Extensions;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace OnLineVideotech.Web.Areas.Admin.Controllers
{
    public class GenreController : BaseAdminController
    {
        private readonly IGenreService genreService;

        public GenreController(IGenreService genreService)
        {
            this.genreService = genreService;
        }

        public async Task<IActionResult> Add()
        {
            GenreViewModel model = new GenreViewModel();
            model.Genres = await this.genreService.GetAllGenres();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(GenreViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Genres = await this.genreService.GetAllGenres();

            if (model.Genres.Any(x => x.Name.ToLower() == model.Name.ToLower()))
            {
                TempData.AddErrorMessage($"Genre with name '{model.Name}' already exists !");
            }
            else
            {
                await this.genreService.Create(model.Name);
                TempData.AddSuccessMessage($"Genre '{model.Name}' successfully created !");
            }

            return RedirectToAction(nameof(Add));
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GenreServiceModel genre = await this.genreService.FindGenre(id);
            GenreViewModel genreViewModel = new GenreViewModel
            {
                Id = genre.Id,
                Name = genre.Name
            };

            return View(genreViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(GenreViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Genres = await this.genreService.GetAllGenres();

            if (model.Genres.Any(x => x.Name == model.Name))
            {
                TempData.AddErrorMessage($"Genre with name '{model.Name}' already exists !");

                return RedirectToAction(nameof(Edit));
            }
            else
            {
                GenreServiceModel genreServiceModel = new GenreServiceModel
                {
                    Id = model.Id,
                    Name = model.Name
                };

                await this.genreService.UpdateGenre(genreServiceModel);

                TempData.AddSuccessMessage($"Genre '{model.Name}' successfully updated !");

                return RedirectToAction(nameof(Add));
            }
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Add));
            }

            GenreServiceModel genre = await this.genreService.FindGenre(id);

            if (genre.Name == null)
            {
                return RedirectToAction(nameof(Add));
            }

            GenreViewModel genreViewModel = new GenreViewModel
            {
                Id = genre.Id,
                Name = genre.Name
            };

            return View(genreViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(GenreViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            GenreServiceModel genreServiceModel = new GenreServiceModel
            {
                Id = model.Id,
                Name = model.Name
            };

            await this.genreService.Delete(genreServiceModel);

            TempData.AddSuccessMessage($"Genre '{model.Name}' successfully deleted !");

            return RedirectToAction(nameof(Add));
        }
    }
}

OnLineVideotech/OnLineVideotech.Web/Areas/Admin/Controllers/HistoryAdminController.cs
using Microsoft.AspNetCore.Mvc;
using OnLineVideotech.Services.Interfaces;
using OnLineVideotech.Services.ServiceModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnLineVideotech.Web.Areas.Admin.Controllers
{
    public class HistoryAdminController : BaseAdminController
    {
        private readonly IHistoryService historyService;

        public HistoryAdminController(IHistoryService historyService)
        {
            this.historyService = historyService;
        }

        public async Task<IActionResult> History()
        {
            List<HistoryServiceModel> histories = await this.historyService.GetHistory();

            return View(histories);
        }

        [HttpPost]
        public async Task<IActionResult> History(HistoryServiceModel model)
        {
            List<HistoryServiceModel> histories = await this.historyService.GetHistory();

            return View(histories);
        }
    }
}

OnLineVideotech/OnLineVideotech.Web/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnLineVideotech.Data.Models;
using OnLineVideotech.Services.Admin.Interfaces;
using OnLineVideotech.Services.Admin.ServiceModels;
using OnLineVideotech.Services.Interfaces;
using OnLineVideotech.Services.ServiceModels;
using OnLineVideotech.Web.Infrastructure;
using OnLineVideotech.Web.Infrastructure.Extensions;
using OnLineVideotech.Web.Models;

namespace OnLineVideotech.Web.Controllers
{
    public class MovieController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly RoleManager<Role> roleManager;
        private readonly IMovieService movieService;
        private readonly IUserBalanceService userBalanceService;
        private readonly ICommentService commentService;
        private readonly IHistoryService historyService;
        private readonly IGenreService genreService;

        public MovieController(UserManager<User> userManager,
            RoleManager<Role> roleManager,
            IMovieService movieService,
            IUserBalanceService userBalanceService,
            ICommentService commentService,
            IHistoryService historyService,
            IGenreService genreService)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.movieService = movieService;
            this.userBalanceService = userBalanceService;
            this.commentService = commentService;
            this.historyService = historyService;
            this.genreService = genreService;
        }

        public async Task<IActionResult> Index()
        {
            MovieFilterServiceModel movieFilterServiceModel = new MovieFilterServiceModel();
            List<MovieServiceModel> movies = await this.movieService.GetMovies();
            List<GenreServiceModel> genres = await genreService.GetAllGenres();

            movieFilterServiceModel.MovieCollection = movies;

            if (User.Identity.IsAuthenticated)
            {
                User user = await userManager.GetUserAsync(HttpContext.User);
                IList<string> roles = await userManager.GetRolesAsync(user);
                string role = roles.SingleOrDefault();              

                if (role == null)
                {
                    await this.userManager.AddToRoleAsync(user, GlobalConstants.RegularUser);

                    role = GlobalConstants.RegularUser;
                }

                foreach (MovieServiceModel movie in movies)
                {
                    MovieServiceModel movieModel = await this.movieService.FindMovie(movie.Id);

                    movie.IsPurchased = this.movieService.IsPurchased(user.Id, movie.Id);

                    movie.Price = movieModel.Prices.SingleOrDefault(x => x.Role.Name == role).MoviePrice;
                }

                foreach (GenreServiceModel genre in genres)
                {
                    GenreServiceModel genreModel = new GenreServiceModel();
                    genreModel.Name = genre.Name;
                    genreModel.Id = genre.Id;
                    movieFilterServiceModel.Genres.Add(genreModel);
                }              
            }

            return View(movieFilterServiceModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(MovieFilterServiceModel movieFilter)
        {
            MovieFilterServiceModel movieFilterServiceModel = await this.movieService.FilteredMovies(movieFilter);
            List<GenreServiceModel> genres = await genreService.GetAllGenres();

            if (User.Identity.IsAuthenticated)
            {
                User user = await userManager.GetUserAsync(HttpContext.User);
                IList<string> roles = await userManager.GetRolesAsync(user);
                string role = roles.SingleOrDefault();

                if (role == null)
                {
                    await this.userManager.AddToRoleAsync(user, GlobalConstants.RegularUser);

                    role = GlobalConstants.RegularUser;
                }

                if (movieFilterServiceModel.MovieCollection != null)
                {
                    foreach (MovieServiceModel movie in movieFilterServiceModel.MovieCollection)
                    {
                        MovieServiceModel movieModel = await this.movieService.FindMovie(movie.Id);

                        movie.IsPurchased = this.movieService.IsPurchased(user.Id, movie.Id);

                        movie.Price = movieModel.Prices.SingleOrDefault(x => x.Role.Name == role).MoviePrice;
                    }
                }
                else
                {
                    movieFilterServiceModel.MovieCollection = new List<MovieServiceModel>();
                }

                foreach (GenreServiceModel genre in genres)
                {
                    GenreServiceModel genreModel = new GenreServiceModel();
                    genreModel.Name = genre.Name;
                    genreModel.Id = genre.Id;
                    movieFilterServiceModel.Genres.Add(genreModel);
                }
            }

            return View(movieFilterServiceModel);
        }

        public async Task<IActionResult> MovieDetails(Guid id)
        {
            MovieServiceModel movieModel = await this.movieService.FindMovie(id);

            movieModel.NumLinesSummary = Regex.Matches(movieModel.Summary, "\r\n").Count;
            movieModel.NumLinesSummary = movieModel.NumLinesSummary + movieModel.NumLinesSummary + 1;

            movieModel.Comments = await this.commentService.GetAllCommentsForMovie(movieModel.Id);
            movieModel.Comments = movieModel.Comments
                .OrderByDescending(x => x.Date)
                .ThenBy(p => p.Date.Hour)
                .ThenBy(c => c.Date.Minute)
                .ThenBy(s => s.Date.Second)
                .ToList();           

            if (User.Identity.IsAuthenticated)
            {
                User user = await userManager.GetUserAsync(HttpContext.User);

                movieModel.History = await this.historyService.GetHistoryForMovieAboutUser(user.Id, id);

                IList<string> roles = await userManager.GetRolesAsync(user);

                foreach (string role in roles)
                {
                    movieModel.Price = movieModel.Prices.SingleOrDefault(x => x.Role.Name == role).MoviePrice;
                }

                movieModel.IsPurchased = this.movieService.IsPurchased(user.Id, movieModel.Id);
            }

            return View(movieModel);
        }

        [Authorize]
        public IActionResult BuyMovie(Guid id)
        {
            BuyMovieViewModel buyMovieViewModel = new BuyMovieViewModel();
            buyMovieViewModel.MovieId = id;

            return View(buyMovieViewModel);
        }

        [Authorize]
        public async Task<IActionResult> PayWithCard(Guid id)
        {
            BuyMovieViewModel buyMovieViewModel = await GetPaymentModel(id);

            return View(buyMovieViewModel);
        }

        [Authorize]
        public async Task<IActionResult> PayFromBalance(Guid id)
        {
            BuyMovieViewModel buyMovieViewModel = await GetPaymentModel(id);

            return View(buyMovieViewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PayFromBalance(BuyMovieViewModel buyMovieViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(buyMovieViewModel);
            }

            User user = await userManager.GetUserAsync(HttpContext.User);

            UserBalanceServiceModel userBalance = this.userBalanceService.GetUserBalance(user.Id);

            if (userBalance.Balance < buyMovieViewModel.Price || userBalance.Balance == 0)
            {
                TempData.AddErrorMessage("You don't have enough money in your account !");

                return RedirectToAction(nameof(PayFromBalance), new { id = buyMovieViewModel.MovieId });
            }

            await this.movieService.BuyMovie(user.Id, buyMovieViewModel.MovieId, buyMovieViewModel.Price);

            TempData.AddSuccessMessage($"Your purchase was successful!");

            return RedirectToAction(nameof(MovieDetails), new { id = buyMovieViewModel.MovieId });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> Library()
        {
            User user = await userManager.GetUserAsync(HttpContext.User);

            IEnumerable<MovieServiceModel> movies = await this.movieService.GetAllPurchasedMoviesForUser(user.Id);

            return View(movies);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateComment(MovieServiceModel model)
        {
            if (!ModelState.IsValid)
            {
                //var errors = ModelState.Select(x => x.Value.Errors)
                //           .Where(y => y.Count > 0)
                //           .ToList();

                return RedirectToAction(nameof(MovieDetails), new { id = model.Id });
            }

            User user = await userManager.GetUserAsync(HttpContext.User);

            await this.commentService.AddCommentForMovie(model.Comment, user.Id, model.Id);

            return RedirectToAction(nameof(MovieDetails), new { id = model.Id });
        }

        [Authorize]
        public async Task<IActionResult> DeleteComment(Guid id)
        {
            CommentServiceModel commentModel = await this.commentService.FindComment(id);

            return View(commentModel);
        }

        [Authorize]
        [HttpPost]

OnLineVideotech/OnLineVideotech.Web/Controllers/UserBalanceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnLineVideotech.Data.Models;
using OnLineVideotech.Services.Interfaces;
using OnLineVideotech.Services.ServiceModels;
using OnLineVideotech.Web.Infrastructure.Extensions;
using OnLineVideotech.Web.Models;
using System.Threading.Tasks;

namespace OnLineVideotech.Web.Controllers
{
    public class UserBalanceController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IUserBalanceService userBalanceService;

        public UserBalanceController(UserManager<User> userManager, IUserBalanceService userBalanceService)
        {
            this.userManager = userManager;
            this.userBalanceService = userBalanceService;
        }

        [Authorize]
        public async Task<IActionResult> Balance()
        {
            User user = await userManager.GetUserAsync(HttpContext.User);          

            UserBalanceServiceModel userBalanceModel = new UserBalanceServiceModel();

            userBalanceModel = this.userBalanceService.GetUserBalance(user.Id);

            return View(userBalanceModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Balance(UserBalanceServiceModel userBalanceModel)
        {
            if (!ModelState.IsValid)
            {
                return View(userBalanceModel);
            }

            User user = await userManager.GetUserAsync(HttpContext.User);

            await this.userBalanceService.AddAmount(userBalanceModel, user.Id);

            TempData.AddSuccessMessage($"Successfully added {userBalanceModel.Balance} BGN to your account");

            return RedirectToAction(nameof(Balance));
        }
    }
}

OnLineVideotech/OnLineVideotech.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnLine Videotech</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-xl navbar-light bg-light">
            <div class="container">
                <img src="~/Hadezign-Hobbies-Movies.ico" class="navbar-toggler-icon" />
                <a class="navbar-brand nav-item" asp-area="" asp-controller="Movie" asp-action="Index">OnLine Videotech</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(GlobalConstants.AdministratorRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="MovieManagement" asp-action="CreateMovie">New movie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Genre" asp-action="Add">Genre manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="HistoryAdmin" asp-action="History">History</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="UserBalance" asp-action="Balance">Balance</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Movie" asp-action="Library">Library</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @if (TempData.ContainsKey(GlobalConstants.TempDataSuccessMessageKey))
            {
                <div class="alert alert-success">
                    @TempData[GlobalConstants.TempDataSuccessMessageKey]
                </div>
            }

            @if (TempData.ContainsKey(GlobalConstants.TempDataErrorMessageKey))
            {
                <div class="alert alert-danger">
                    @TempData[GlobalConstants.TempDataErrorMessageKey]
                </div>
            }

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - OnLine Videotech - <a asp-area="" asp-controller="Movie" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>